#!/bin/bash

NAME=\”/Users/MichaelRyan/Documents/Programming/Github/vexquery-skill/helperCommands\”
HOME_NAME=\”/Users/MichaelRyan/Documents/Programming/Github/vexquery-skill\”
pwd=\”$PWD\”

if [[ $pwd == $NAME ]]; then
	cd ..
fi

pwd=\”$PWD\”

echo $pwd
echo $HOME_NAME

if [[ $pwd == $HOME_NAME ]]; then
	cd src

	echo Zipping…

	zip -r vexquery.zip index.js node_modules package.json

	cd ..

	mv src/vexquery.zip deployment/vexquery.zip

	echo Done
else
	echo Not in proper directory to run this command!
	
	echo Please navigate to $HOME_NAME
fi

